# [REQUIRED] All Jump'n'Runs that you want to have
# - To create a new Jump'n'Run, add a key that should uniquely identify your Jump'n'Run to the jnrs section.
jnrs:
  # An example Jump'n'Run for showing all the different settings
  example:
    # [REQUIRED] The Name that should be displayed ingame
    # - doesn't have to be unique
    name: §14Lobby JNR

    # The world in that the plugin should search for the pressure plate locations.
    # - if you haven't changed anything with your world settings or names, you can just leave this out
    #   and it will default to "world"
    world: world

    # [REQUIRED] Whether this Jump'n'Run is enabled or not
    enabled: false

    # [REQUIRED] The location of the pressure plate, that players have to step on to start the Jump'n'Run
    # - This has to be the location of any kind of pressure plate
    # - For the holograms to work correctly, add .5 to the x and z coordinates.
    # - Format: x y z
    start: 0 0 0

    # [REQUIRED] The location of the pressure plate, that players have to step on to end their run
    # - This has to be the location of any kind of pressure plate
    # - For the holograms to work correctly, add .5 to the x and z coordinates.
    # - Format: x y z
    end: 0 0 0

    # A list of locations of the checkpoints for this Jump'n'Run
    # - The entries have to be locations of any kind of pressure plates
    # - The checkpoint are numbered by indices of this list
    # - if your Jump'n'Run shouldn't have any checkpoints, just leave this out
    # - Format: x y z
    checkpoints:
      - 0 0 0
      - 1 1 1

    # [REQUIRED] The location of the sign that should display the current highscore of the Jump'n'Run
    highscoreSign:
      # [REQUIRED] whether the sign location is correct and should be used
      enabled: false

      # The coordinates of the Highscore sign
      #  - Format: x y z
      coords: 0 0 0

    # Whether to teleport the player to their latest checkpoint when they fall in lave
    cancelInLava: true

# [REQUIRED] The file location of the SQLite database to store the highscore information for every player
# - in the most cases, you don't have to change this
database: db.db

# The messages to send to players on specific events
# - all messages have default values so you don't have to set any of them
messages:
  # Displayed when a player flew during the Jump'n'Run
  fly: "Jump'n'Run challenge ended because you flew!"

  # Hologram text for the start pressure plate
  startHolo: "§aStart"

  # Hologram text for the end pressure plate
  endHolo: "§aEnd"

  # Displayed when a player started the Jump'n'Run
  start: "Jump'n'Run started!"

  # Displayed when a player stepped on the start pressure plate while doing the Jump'n'Run
  reset: "Your time has been reset"

  # Displayed when a player stepped on a checkpoint before starting the Jump'n'Run
  gotostart: "Go to the §eStart Plate §7to start the Jump'n'Run"

  # Displayed when a player finished the Jump'n'Run
  # - %time% => The time that was needed to complete the Jump'n'Run
  #             Example: 00:58:450
  finished: "You finished the Jump'n'Run in §6%time%§7!"

  # Displayed when a player beat their personal best
  # - %time% => The time that was beaten by this run
  #             Example: 00:58:450
  pb: "§a§lThat's a new personal record! Your previous time was §6%time%§7!"

  # Broadcasted when a player set a new global highscore for the Jump'n'Run
  # - %time%   => The time that was needed to complete the Jump'n'Run
  #               Example: 00:58:450
  # - %player% => The name of the player that beat the highscore
  #               Example: xImAnton_
  highscore: "§e§l%player%§r§a set a new Highscore of §6§l%time%§r§a!"

  # Displayed when a player reached a checkpoint
  # - %checkpoint% => The number of the checkpoint
  #                   Example: 2
  # - %time%       => The time for that a player was playing the Jump'n'Run before it reached this checkpoint
  #                   Example: 00:58:450
  checkpoint: "Checkpoint §a#%checkpoint%§7 reached after §6%time%§7!"

  # Text for the item that is used to go back to the last checkpoint
  backToCheckpoint: "§7Back to §aCheckpoint"

  # Text for the item that is used to reset to the start of the Jump'n'Run
  backToStart: "§7Back to §aStart"

  # Text for the item that is used to quit the Jump'n'Run
  quit: "§cQuit Jump'n'Run"